// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFanLevelChange();
void onWaterLevelChange();
void onPowerHumidifierChange();

CloudDimmedLight fanLevel;
CloudDimmedLight waterLevel;
CloudSwitch powerHumidifier;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(fanLevel, READWRITE, ON_CHANGE, onFanLevelChange, 3);
  ArduinoCloud.addProperty(waterLevel, READWRITE, ON_CHANGE, onWaterLevelChange, 2);
  ArduinoCloud.addProperty(powerHumidifier, READWRITE, ON_CHANGE, onPowerHumidifierChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
